spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/textbook_trading?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

#    url: jdbc:mysql://47.98.37.172:3309/textbook_trading?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    username: hjbj
#    password: hjbj123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
